### ISSUE TITLE
想通过fetch获取省市，然后react设置setState，但是不行

### ISSUE THREAD

**Issue by masonyeh** [petitspois/react-picker#1]
我想通过fetch 从后台接口中获取省市信息，但是通过setState 重新渲染赋值setData改变原来初始的值 好像是不行，还使用forceUpdate去渲染子组件，也是不行，可以解决这个问题？

import React, { Component } from 'react'
import {CityPicker,DatePicker} from 'react-pickers'
import '../../../css/elements/picker.css'

import city2 from './lib/city-data'

class Picker extends Component {

  componentDidMount(){
    let __self = this

```
this.setState({city:[{
  value: '110000',
  text: '北京市',
  children: [{
    value: "110101",
    text: "sdfsdf"
  }]
}]})


this.getStateInfo(function(data){
    let city = []

    for(let i=0;i<data.length;i++){
        let obj = new Object();
        obj.value=String(data[i]['id']);
        obj.text=data[i]['name'];
        obj.children=[];
        let citys= data[i]['citys']

        for(let index=0;index<citys.length;index++){
           let aObj = new Object();
             aObj.value=String(citys[index]['id']);
             aObj.text=citys[index]['name'];
             obj.children.push(aObj);
         }
        city.push(obj);
    }
   __self.setState({city:city})
   __self.forceUpdate(function(e){
     console.log('eeeeee',e)
   });
  //  console.log('force',city)

})
```

  }

  getStateInfo(callback){

```
fetch("/city/statejson",  {
      credentials: 'include',
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({})
  }).then(function(res) {
     return res.json()
  }, function(e) {
    console.log("Error submitting form!");
  }).then(function(data){
      if(data.result.success){
        callback(data.result.data)
      }
  });
```

  }

  state = {
      showCity2Picker:false,
      city: [{
        value: '110000',
        text: '北京市',
        children: [{
            value: "110101",
            text: "东城区"
        }]
      }]
  }

  showCity2Picker(){
      this.setState({showCity2Picker: true })
  }

  ok2(){
      this.setState({showCity2Picker: false })
  }

  cl2(){
      this.setState({showCity2Picker: false })
  }
  getData2(ret){
      console.log("你选择的城市是:" + ret[0].text + " " + ret[1].text);
  }

  render() {
console.log('render',this.state.city)
      return (
        <div>
              <h5 className="mui-content-padded">级联示例</h5>
              <button id='showCityPicker' className="mui-btn mui-btn-block" type='button' onClick={ this::this.showCity2Picker  }>二级联动示例 ...</button>
              <CityPicker visible={ this.state.showCity2Picker } layer='2' setData={this.state.city?this.state.city:''}
                getData={ this::this.getData2 } confirm={ this::this.ok2 } cancel={ this::this.cl2 } />
          </div>
      )
  }
}

module.exports = Picker

**Comment by petitspois** [comment]
这是MUI的一个方法里面是需要new，数据要提前给，不能异步。可以直接import json

**Comment by masonyeh** [comment]
import json 也只是能生成好的文件是吗？

**Comment by masonyeh** [comment]
import json 也只是能生成好的文件是吗？ @petitspois

**Comment by masonyeh** [comment]
我已经完成异步了，

componentDidMount(){
    let __self = this

```
this.getStateInfo(function(data){
    let city = []

    for(let i=0;i<data.length;i++){
        let obj = new Object();
        obj.value=String(data[i]['id']);
        obj.text=data[i]['name'];
        obj.children=[];
        let citys= data[i]['citys']

        for(let index=0;index<citys.length;index++){
           let aObj = new Object();
             aObj.value=String(citys[index]['id']);
             aObj.text=citys[index]['name'];
             obj.children.push(aObj);
         }
        city.push(obj);
    }
     __self.setState({city:city}) 
})
```

  }

  getStateInfo(callback){

```
fetch("/province/city/statejson",  {
      credentials: 'include',
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({})
  }).then(function(res) {
     return res.json()
  }, function(e) {
    console.log("Error submitting form!");
  }).then(function(data){
      if(data.result.success){
        callback(data.result.data)
      }
  });
```

  }

  state = {
      showCity2Picker:false,
      city: []
  }

  render() {

>   由于这个Picker只能第一次赋值，不能出现再次赋值，起初我想是不是父组件render时，子组件是不render的，我接着使用了 forceUpdate()强行深度render所有相关子组件，结果也不行， 最后我采用了初始state.city 为空，render判断它 如果为空就不渲染它，在当前picker组件渲染后 就去请求省市数据，当拿到数据后，setState({city:newData}) 这样下面的picker就可以渲染出来了；再次很谢谢你写的这个库;

```
  # let picker = "";
  if(this.state.city.length){
    picker = (<CityPicker visible={ this.state.showCity2Picker } layer='2' setData={this.state.city?this.state.city:''}
      getData={ this::this.getData2 } confirm={ this::this.ok2 } cancel={ this::this.cl2 } />)
  }

  return (
    <div>
          <h5 className="mui-content-padded">级联示例</h5>
          <button id='showCityPicker' className="mui-btn mui-btn-block" type='button' onClick={ this::this.showCity2Picker  }>二级联动示例 ...</button>
          {picker}
      </div>
  )
```

  }
