### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by MasonChow** [petitspois/react-picker#2]
index.js 里面require datapicker与citiypick在文件命名大小写有错误

**Comment by petitspois** [comment]
index.js webpack自动生成的

**Comment by MasonChow** [comment]
现在情况就是install之后  要去改动一下才能用 不然就会报错can not find module

**Comment by petitspois** [comment]
es5的写法吗？晚上看看

**Comment by MasonChow** [comment]
OK  只要install新跑一次就可以发现报错了

**Comment by petitspois** [comment]
@BryantZhou 这个问题已经解决
