### ISSUE TITLE
字体是蓝色的

### ISSUE THREAD

**Issue by baicuhaha** [petitspois/react-picker#4]
在使用DatePicker的时候！月份会变成蓝色。日期有时候也会变成蓝色！
![img_0443](https://cloud.githubusercontent.com/assets/20334376/24086926/d04a79be-0d52-11e7-9051-59706749fd08.PNG)
这是为什么？

**Comment by petitspois** [comment]
看不到代码不好说，这是带a标签了

**Comment by baicuhaha** [comment]
这个已解决了 是ios把它当成号码了！但是现在还有个问题。。就是软键盘弹出的时候！再点击其他按钮！软键盘回收！回收的时候发现picker已经出现在底部了！是不是软键盘弹出的时候，flex布局失效造成了吗？

**Comment by baicuhaha** [comment]
我在Safari浏览器上面没有发现这个问题！但是在qq和微信上面都有这个问题！ios和安卓我都测了几遍都有这个问题。。。

**Comment by petitspois** [comment]
根据页面的高度，控制定位。
